version: '2'
services:

    mongo:
        image: mongo:3.4
        restart: always
        volumes:
            - "learninglocker_data:/data/db"

    redis:
        image: redis:4-alpine
        restart: always

    xapi:
        image: learninglocker/xapi-service:2.0.1
        restart: always
        environment:
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - REDIS_URL=redis://redis:6379/0
            - REDIS_PREFIX=xapi_learninglocker
        depends_on:
            - mongo
            - redis

    learninglocker:
        image: hoangvubrvt/learninglocker:2.1.1
        restart: always
        depends_on:
            - mongo
            - redis
        volumes:
            - "learninglocker_storage:/opt/learninglocker/storage"
        
    nginx:
        build: nginx
        restart: always
        depends_on:
            - learninglocker
            - xapi
        ports:
            - "80:80"


volumes: 
    learninglocker_data: {}
    learninglocker_storage: {}